tornado.database error when running inside PyPy
