Traceback (most recent call last):
  File "app_main.py", line 53, in run_toplevel
  File "./app.py", line 5, in <module>
    import tornado.database
  File "/path/to/app/pypy/pypy-env/site-packages/tornado/database.py", line 183, in <module>
    CONVERSIONS = copy.deepcopy(MySQLdb.converters.conversions)
  File "/path/to/app/pypy/pypy-c-jit-43780-b590cf6de419-osx64/lib-python/2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/path/to/app/pypy/pypy-c-jit-43780-b590cf6de419-osx64/lib-python/2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/path/to/app/pypy/pypy-c-jit-43780-b590cf6de419-osx64/lib-python/2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/path/to/app/pypy/pypy-c-jit-43780-b590cf6de419-osx64/lib-python/2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
  File "/path/to/app/pypy/pypy-env/lib-python/2.7/copy_reg.py", line 93, in __newobj__
    return cls.__new__(cls, *args)
TypeError: object.__new__(builtin_function_or_method) is not safe, use builtin_function_or_method.__new__()
